exclude: '^vendor/'
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-added-large-files
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
- repo: https://github.com/dnephin/pre-commit-golang
  rev: v0.5.0
  hooks:
    - id: go-fmt
    - id: go-mod-tidy
    - id: go-mod-vendor
ci:
  autofix_prs: false
  autoupdate_branch: 'pre-commit.ci-autoupdate'
  autoupdate_schedule: 'quarterly'
