#!/bin/bash

VERSION=20160608

# check certificates for expiration

TEST=${1}

  LOG=${HOME}/maint/checkcerts.log
ALARM=${HOME}/maint/checkcerts.alarm
 LIST=${HOME}/maint/checkcerts.list

MAILTO=fermigrid-help@fnal.gov

WARN=30

rm -f ${ALARM}
touch ${ALARM}


printf "\ncheckcerts ${VERSION} `date`\n" >> ${LOG}

{
CERTDIR=/var/lib/jobsub/creds/certs

cd ${CERTDIR}

PRS=`ls *.cert | cut -f 1 -d .`

for PR in ${PRS} ; do
    EXP=`openssl x509 -noout -in ${PR}.cert -enddate | cut -f 2- -d =`
    SUB=`openssl x509 -noout -in ${PR}.cert -subject | cut -f 2- -d =`
    EXS=`date +%s -d "${EXP}"`
    NOW=`date +%s`
    (( EXD = ( EXS - NOW ) / 86400 ))
    printf "%15s %5d ${SUB}\n" ${PR} ${EXD}
    [ ${EXD} -lt ${WARN} ] && \
    printf "%15s %5d ${SUB}\n" ${PR} ${EXD} > ${ALARM}
done | sort -n -k 2
} > ${LIST} 2>&1

cat ${LIST} >> ${LOG}

NALARM=`wc -l ${ALARM} | cut -f 1 -d ' '`

if [ -n "${TEST}" ] ; then
    if [ ${NALARM} -eq 0 ] ; then
        { echo "All Is Well" ; head -1 ${LIST} ; }  
    else
        { echo "jobsub certs expiring" ; cat ${ALARM} ; }
    fi
else
    if [ ${NALARM} -eq 0 ] ; then
        { echo "All Is Well - next expiration is" ; head -1 ${LIST} ; }        | /bin/mail -s "checkcerts report - no issues"  ${MAILTO}
    else
        { echo "jobsub certs expiring" ; cat ${ALARM} ; } | /bin/mail -s "checkcerts report - ${NALARMS} ALARMS" ${MAILTO}
    fi
fi

exit

20160608   kreymer
Added echo in test mode
Added next cert to expire to good report

20160602   kreymer
changed mail from kreymer to fermigrid-help

20160528   kreymer
created
