# Global config items

# Logging/Error handling files.
logs:
  logfile:  proxy_push.log
  errfile:  proxy_push.err      # Set the temporary output file for errors.  


# Global email and slack notification parameters
notifications:
  SLACK_ALERTS_URL:  'https://hooks.slack.com/services/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'      # Slack url for #alerts channel in fife-group slack
  admin_email: fife-group@fnal.gov
 

# Same as above, but used in test runs
notifications_test:
  SLACK_ALERTS_URL: 'https://hooks.slack.com/services/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'      # Slack url for #alerts-dev channel in fife-group slack.  Use for testing
  admin_email: sbhat@fnal.gov
  # admin_email: kherner@fnal.gov
  

# Other config variabless
global:
  should_runuser: rexbatch                                    # User that this script must run as 
  KRB5CCNAME:  "FILE:/tmp/krb5cc_push_proxy"  # What the env variable KRB5CCNAME should be set to
  CERT_BASE_DIR: "/opt/gen_push_proxy/certs"                      # base location for certs/keys
  expt_vos: ["des", "dune"]                         # Experiments that have their own VOMS server


# Experiments
# Note: roles entries should be of the form "- Role_name: Role_account"
experiments:
  coupp:
    dir: /opt
    emails: [hugh@fnal.gov]
    nodes: [couppgpvm01, couppgpvm02]
    roles:
      - Production: coupp
  darkside:
    dir: /opt
    emails: [kherner@fnal.gov]
    nodes: [ds50samgpvm01]
    roles:
      - Production: darksidepro
  des:
    dir: /opt
    emails: [buckley@fnal.gov]
    nodes: [des40, des41, des50, des51, des60, des61]
    roles:
      - DESGW: desgw
  dune:
    dir: /opt
    emails: [trj@fnal.gov]
    nodes: [dunegpvm01, dunegpvm02, dunegpvm03, dunegpvm04, dunegpvm05, dunegpvm06,
      dunegpvm07, dunegpvm08, dunegpvm09, dunegpvm10, dunesamgpvm02]
    roles:
      - Production: dunepro
  genie:
    dir: /opt
    emails: [perdue@fnal.gov]
    nodes: [geniegpvm01]
    roles:
      - Production: geniepro
  gm2:
    dir: /opt
    emails: [lyon@fnal.gov]
    nodes: [gm2gpvm01, gm2gpvm02, gm2gpvm03, gm2gpvm04, gm2samgpvm01]
    roles:
      - Production: gm2pro
  lariat:
    dir: /opt
    emails: [wenzel@fnal.gov]
    nodes: [lariatsamgpvm01]
    roles:
      - Production: lariatpro
  minerva:
    dir: /opt
    emails: [perdue@fnal.gov]
    nodes: [minervagpvm01, minervagpvm02, minervagpvm03, minervagpvm04, minervagpvm05,
      minervagpvm06, minervagpvm07]
    roles:
      - Calibration: minervacal
      - Production: minervapro
      - Data: minervadat
  minos:
    dir: /opt
    emails: [kreymer@fnal.gov]
    nodes: [minosdatagpvm01, minosgpvm05]
    roles:
      - Production: minospro
  mu2e:
    dir: /opt
    emails: [kutschke@fnal.gov, rlc@fnal.gov, gandr@fnal.gov]
    nodes: [mu2egpvm01, mu2egpvm02, mu2egpvm03, mu2egpvm04, mu2egpvm05, mu2egpvm06]
    roles:
      - Production: mu2epro
  nova:
    dir: /opt
    emails: [dingpf@fnal.gov]
    nodes: [novagpvm01, novagpvm02, novagpvm03, novagpvm04, novagpvm05, novagpvm06,
      novagpvm07, novagpvm08, novagpvm09, novagpvm10, novagpvm11, novagpvm12, novagpvm13,
      novagpvm14, novagpvm15, novadqgpvm01]
    roles:
      - Production: novapro
  sbnd:
    dir: /opt
    emails: [petrillo@fnal.gov]
    nodes: [sbndgpvm01, sbndgpvm02, sbndgpvm03]
    roles:
      - Production: sbndpro
  uboone:
    dir: /opt
    emails: [kirby@fnal.gov]
    nodes: [uboonegpvm01, uboonegpvm02, uboonegpvm03, uboonegpvm04, uboonegpvm05, uboonegpvm06,
      uboonegpvm07, uboonepubsgpvm01, uboonepubsgpvm02, uboonepubsgpvm03, uboonepubsgpvm04,
      uboonepubsgpvm05, uboonepubsgpvm06]
    roles:
      - Production: uboonepro
