# Global config items

# Timeouts
timeout:
  globalTimeout: 60s # Global timeout
  exptTimeout:   60s # Experiment timeout
  pingTimeout:   10s # Ping timeout (for all pings per experiment)
  vpiTimeout:    10s # voms-proxy-init timeout (total for vpis per experiment)
  copyTimeout:   20s # copy proxy timeout (total for all copies per experiment)
  slackTimeout:  15s # Slack message timeout
  emailTimeout:  30s # Email timeout (per email)


# Logging/Error handling files.
logs:
  logfile:  golang_proxy_push.log
  errfile:  golang_proxy_push.err      # Set the temporary output file for errors.  
  debugfile: golang_proxy_push.debug.log


# Global email and slack notification parameters
notifications:
  SLACK_ALERTS_URL:  "https://hooks.slack.com/services/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"      # Slack url for #alerts channel in fife-group slack
  # admin_email: fife-group@fnal.gov
  admin_email: shreyb@gmail.com
 

# Same as above, but used in test runs
notifications_test:
  SLACK_ALERTS_URL: "https://hooks.slack.com/services/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"      # Slack url for #alerts-dev channel in fife-group slack.  Use for testing
  admin_email: sbhat@fnal.gov
  # admin_email: kherner@fnal.gov
  

# Other config variabless
global:
  should_runuser: rexbatch                                    # User that this script must run as 
  KRB5CCNAME:  "FILE:/tmp/krb5cc_push_proxy"  # What the env variable KRB5CCNAME should be set to
  CERT_BASE_DIR: "/opt/gen_push_proxy/certs"                      # base location for certs/keys
  # expt_vos: ["des", "dune"]                         # Experiments that have their own VOMS server


# Experiments
# Note: accounts entries should be of the form "account_name: Role_name"
experiments:
  coupp:
    dir: /opt
    # emails: [hugh@fnal.gov]
    emails: [sbhat@fnal.gov]
    nodes: [couppgpvm01, couppgpvm02]
    accounts:
      coupp: Production
  darkside:
    dir: /opt
    # emails: [kherner@fnal.gov]
    emails: [sbhat@fnal.gov]
    # nodes: [ds50samgpvm01]
    nodes: [ds50samgpvm012345]
    accounts:
      darksidepro: Production
  des:
    dir: /opt
    # emails: [buckley@fnal.gov]
    emails: [sbhat@fnal.gov]
    nodes: [des40, des41, des50, des51, des60, des61]
    accounts:
      desgw: DESGW
    vomsgroup: "des:/des/"
  dune:
    dir: /opt
    # emails: [trj@fnal.gov, fuess@fnal.gov, berman@fnal.gov, anorman@fnal.gov]
    emails: [sbhat@fnal.gov]
    nodes: [dunegpvm01, dunegpvm02, dunegpvm03, dunegpvm04, dunegpvm05, dunegpvm06,
      dunegpvm07, dunegpvm08, dunegpvm09, dunegpvm10, dunesamgpvm02]
    accounts:
      dunepro: Production
    vomsgroup: "dune:/dune/"
  genie:
    dir: /opt
    # emails: [perdue@fnal.gov]
    emails: [sbhat@fnal.gov]
    nodes: [geniegpvm01]
    accounts:
      geniepro: Production
  gm2:
    dir: /opt
    # emails: [lyon@fnal.gov]
    emails: [sbhat@fnal.gov]
    nodes: [gm2gpvm01, gm2gpvm02, gm2gpvm03, gm2gpvm04, gm2samgpvm01]
    accounts:
      gm2pro: Production
  lariat:
    dir: /opt
    # emails: [wenzel@fnal.gov]
    emails: [sbhat@fnal.gov]
    nodes: [lariatsamgpvm01]
    accounts:
      lariatpro: Production
  minerva:
    dir: /opt
    # emails: [perdue@fnal.gov, jyhan@fnal.gov]
    emails: [sbhat@fnal.gov]
    nodes: [minervagpvm01, minervagpvm02, minervagpvm03, minervagpvm04, minervagpvm05,
      minervagpvm06, minervagpvm07]
    accounts:
      minervacal: Calibration
      minervapro: Production
      minervadat: Data
  minos:
    dir: /opt
    # emails: [kreymer@fnal.gov, wingmc@fnal.gov]
    emails: [sbhat@fnal.gov]
    nodes: [minosdatagpvm01, minosgpvm05]
    accounts:
      minospro: Production
  mu2e:
    dir: /opt
    # emails: [kutschke@fnal.gov, rlc@fnal.gov, gandr@fnal.gov]
    emails: [sbhat@fnal.gov]
    nodes: [mu2egpvm01, mu2egpvm02, mu2egpvm03, mu2egpvm04, mu2egpvm05, mu2egpvm06]
    accounts:
      mu2epro: Production
  nova:
    dir: /opt
    # emails: [dingpf@fnal.gov]
    emails: [sbhat@fnal.gov]
    nodes: [novagpvm01, novagpvm02, novagpvm03, novagpvm04, novagpvm05, novagpvm06,
      novagpvm07, novagpvm08, novagpvm09, novagpvm10, novagpvm11, novagpvm12, novagpvm13,
      novagpvm14, novagpvm15, novadqgpvm01]
    accounts:
      novapro: Production
  sbnd:
    dir: /opt
    # emails: [petrillo@fnal.gov]
    emails: [sbhat@fnal.gov]
    nodes: [sbndgpvm01, sbndgpvm02, sbndgpvm03]
    accounts:
      sbndpro: Production
  uboone:
    dir: /opt
    # emails: [kirby@fnal.gov, greenlee@fnal.gov, joelam@fnal.gov]
    emails: [sbhat@fnal.gov]
    nodes: [uboonegpvm01, uboonegpvm02, uboonegpvm03, uboonegpvm04, uboonegpvm05, uboonegpvm06,
      uboonegpvm07, uboonepubsgpvm01, uboonepubsgpvm02, uboonepubsgpvm03, uboonepubsgpvm04,
      uboonepubsgpvm05, uboonepubsgpvm06, uboonetmp02]
    accounts:
      uboonepro: Production
  p-larreco:
    dir: /opt/ci_proxy/lar_ci
    # emails: [vito@fnal.gov, sbhat@fnal.gov]
    emails: [sbhat@fnal.gov]
    nodes: [cdcvs, ]
    accounts:
      p-larreco: Analysis
    vomsgroup: "fermilab:/fermilab/uboone/"
    certfile: "/opt/gen_push_proxy/certs/CI-service.cert" 
    keyfile:  "/opt/gen_push_proxy/certs/CI-service.key"
  p-argoneutcode:
    dir: /opt/ci_proxy/lar_ci
    # emails: [vito@fnal.gov, sbhat@fnal.gov]
    emails: [sbhat@fnal.gov]
    nodes: [cdcvs, ]
    accounts:
      p-argoneutcode: Analysis
    vomsgroup: "fermilab:/fermilab/argoneut/"
    certfile: "/opt/gen_push_proxy/certs/CI-service.cert" 
    keyfile:  "/opt/gen_push_proxy/certs/CI-service.key"
  p-lardbt:
    dir: /opt/ci_proxy/lar_ci
    # emails: [vito@fnal.gov, sbhat@fnal.gov]
    emails: [sbhat@fnal.gov]
    nodes: [cdcvs, ]
    accounts:
      p-lardbt: Analysis
    vomsgroup: "fermilab:/fermilab/lariat/"
    certfile: "/opt/gen_push_proxy/certs/CI-service.cert" 
    keyfile:  "/opt/gen_push_proxy/certs/CI-service.key"
  p-larsoft:
    dir: /opt/ci_proxy/lar_ci
    # emails: [vito@fnal.gov, sbhat@fnal.gov]
    emails: [sbhat@fnal.gov]
    nodes: [cdcvs, ]
    accounts:
      p-larsoft: Analysis
    vomsgroup: "fermilab:/fermilab/uboone/"
    certfile: "/opt/gen_push_proxy/certs/CI-service.cert" 
    keyfile:  "/opt/gen_push_proxy/certs/CI-service.key"
